#!/usr/bin/env python3
"""
music2asm.py - Convert tetris_music.c to tetris_music.asm

Parses the hUGEDriver song data from the C source file and outputs
RGBDS-compatible assembly using the dn macro from hUGE.inc.

Usage:
  python3 tools/music2asm.py source/main/tetris_music.c > asm/tetris_music.asm
"""

import re
import sys


def convert_note(note):
    """Convert C note name to ASM note name.

    C uses: As4, Ds5, Gs3 etc. for sharps
    ASM uses: A#4, D#5, G#3 etc.
    Non-sharps (C_5, A_4, ___, etc.) pass through unchanged.
    """
    m = re.match(r'^([A-G])s(\d)$', note)
    if m:
        return f'{m.group(1)}#{m.group(2)}'
    return note


def parse_patterns(c_source):
    """Extract all pattern definitions from C source.

    Returns dict of {name: [(note, instr, effect), ...]}
    """
    patterns = {}
    # Match: static const unsigned char Pxx[] = { ... };
    for m in re.finditer(
        r'static const unsigned char (P\d+)\[\]\s*=\s*\{([^}]+)\}',
        c_source, re.DOTALL
    ):
        name = m.group(1)
        body = m.group(2)
        entries = []
        for dn in re.finditer(r'DN\(\s*(\w+)\s*,\s*(\d+)\s*,\s*(0x[0-9A-Fa-f]+)\s*\)', body):
            note = convert_note(dn.group(1))
            instr = int(dn.group(2))
            effect = '$' + dn.group(3)[2:].upper()
            entries.append((note, instr, effect))
        patterns[name] = entries
    return patterns


def parse_order_tables(c_source):
    """Extract order tables from C source.

    Returns dict of {name: [pattern_name, ...]}
    """
    orders = {}
    for m in re.finditer(
        r'static const unsigned char\*\s*const\s+(order\d)\[\]\s*=\s*\{([^}]+)\}',
        c_source, re.DOTALL
    ):
        name = m.group(1)
        body = m.group(2)
        refs = [x.strip() for x in body.split(',') if x.strip()]
        orders[name] = refs
    return orders


def parse_byte_array(c_source, name):
    """Extract a raw byte array from C source."""
    pattern = rf'static const unsigned char {name}\[\]\s*=\s*\{{([^}}]+)\}}'
    m = re.search(pattern, c_source, re.DOTALL)
    if not m:
        return []
    return [int(x.strip()) for x in m.group(1).split(',') if x.strip()]


def parse_order_cnt(c_source):
    """Extract order_cnt value."""
    m = re.search(r'static const unsigned char order_cnt\s*=\s*(\d+)', c_source)
    return int(m.group(1)) if m else 0


def parse_tempo(c_source):
    """Extract tempo from hUGESong_t constructor."""
    m = re.search(r'hUGESong_t\s+tetris_music\s*=\s*\{(\d+)', c_source)
    return int(m.group(1)) if m else 7


def emit_asm(out, tempo, order_cnt, orders, patterns, duty, wave, noise, waves):
    """Write complete tetris_music.asm."""

    out.write('; =============================================================================\n')
    out.write('; tetris_music.asm - Music data for hUGEDriver (Tetris theme: Korobeiniki)\n')
    out.write('; AUTO-GENERATED by tools/music2asm.py from source/main/tetris_music.c\n')
    out.write('; Do not edit manually - regenerate with: make music\n')
    out.write('; =============================================================================\n\n')

    out.write('INCLUDE "common.inc"\n')
    out.write('INCLUDE "hUGE.inc"\n\n')

    out.write('SECTION "MusicData", ROM0\n\n')

    # Song descriptor
    out.write('; Song descriptor struct (hUGESong_t)\n')
    out.write('_tetris_music::\n')
    out.write(f'    db {tempo}                            ; tempo\n')
    out.write('    dw _order_cnt                   ; pointer to order count\n')
    out.write('    dw _order1, _order2, _order3, _order4\n')
    out.write('    dw _duty_instruments\n')
    out.write('    dw _wave_instruments\n')
    out.write('    dw _noise_instruments\n')
    out.write('    dw 0                            ; routines (NULL)\n')
    out.write('    dw _waves\n\n')

    # Order count
    out.write('_order_cnt:\n')
    out.write(f'    db {order_cnt}\n\n')

    # Order tables
    for i in range(1, 5):
        name = f'order{i}'
        refs = orders[name]
        out.write(f'_order{i}:\n')
        out.write(f'    dw {", ".join(refs)}\n')
    out.write('\n')

    # Duty instruments
    out.write('; Duty instruments (15 instruments x 4 bytes each)\n')
    out.write('_duty_instruments:\n')
    for i in range(0, len(duty), 4):
        chunk = duty[i:i+4]
        out.write(f'    db {", ".join(str(b) for b in chunk)}\n')
    out.write('\n')

    # Wave instruments
    out.write('; Wave instruments (15 instruments x 4 bytes each)\n')
    out.write('_wave_instruments:\n')
    for i in range(0, len(wave), 4):
        chunk = wave[i:i+4]
        out.write(f'    db {", ".join(str(b) for b in chunk)}\n')
    out.write('\n')

    # Noise instruments
    out.write('; Noise instruments (15 instruments x 8 bytes each)\n')
    out.write('_noise_instruments:\n')
    for i in range(0, len(noise), 8):
        chunk = noise[i:i+8]
        out.write(f'    db {", ".join(str(b) for b in chunk)}\n')
    out.write('\n')

    # Waves
    out.write('; Wave data (16 waves x 16 bytes each = 256 bytes)\n')
    out.write('_waves:\n')
    for i in range(0, len(waves), 16):
        chunk = waves[i:i+16]
        out.write(f'    db {", ".join(f"{b:3d}" for b in chunk)}\n')
    out.write('\n')

    # Patterns - emit in sorted order (P0, P1, P2, P3, P10, P11, ...)
    def pattern_sort_key(name):
        num = int(name[1:])
        return num

    sorted_names = sorted(patterns.keys(), key=pattern_sort_key)

    out.write('; =============================================================================\n')
    out.write('; Patterns (64 rows each)\n')
    out.write('; =============================================================================\n\n')

    for name in sorted_names:
        entries = patterns[name]
        out.write(f'{name}:\n')
        for note, instr, effect in entries:
            out.write(f'    dn {note}, {instr}, {effect}\n')
        out.write('\n')


def main():
    if len(sys.argv) < 2:
        print(f'Usage: {sys.argv[0]} <tetris_music.c>', file=sys.stderr)
        sys.exit(1)

    with open(sys.argv[1]) as f:
        c_source = f.read()

    tempo = parse_tempo(c_source)
    order_cnt = parse_order_cnt(c_source)
    orders = parse_order_tables(c_source)
    patterns = parse_patterns(c_source)
    duty = parse_byte_array(c_source, 'duty_instruments')
    wave = parse_byte_array(c_source, 'wave_instruments')
    noise = parse_byte_array(c_source, 'noise_instruments')
    waves = parse_byte_array(c_source, 'waves')

    # Write to file (or stdout)
    if len(sys.argv) >= 3:
        outpath = sys.argv[2]
        with open(outpath, 'w') as out:
            emit_asm(out, tempo, order_cnt, orders, patterns, duty, wave, noise, waves)
        print(f'Generated {outpath}')
    else:
        emit_asm(sys.stdout, tempo, order_cnt, orders, patterns, duty, wave, noise, waves)


if __name__ == '__main__':
    main()
