#!/usr/bin/env python3
"""
png2asm.py - Convert png2asset C output to RGBDS assembly data.

Parses the structured C files generated by png2asset and outputs:
  1. gfx/sprite_defs.inc    - tile count DEF constants (with include guard)
  2. gfx/sprite_data.inc    - tile data, metasprites, pointer table, tile offsets
  3. gfx/palette_data.inc   - CGB palette data as raw bytes (64 bytes, RGB555 LE)
  4. gfx/setup_sprites.inc  - set_sprite_data call sequences for all pieces

Usage:
  python3 tools/png2asm.py gfx/gen/Tetromino1.c ... gfx/gen/Tetromino7.c [gfx/gen/Pentomino1.c ...] gfx/gen/Palette.c

The output files are written to the gfx/ directory (same parent as the input .c files).
"""

import re
import sys
import os


def rgb8_to_rgb555(r, g, b):
    """Convert 8-bit RGB to CGB RGB555 (little-endian uint16)."""
    return (b >> 3) << 10 | (g >> 3) << 5 | (r >> 3)


def parse_tile_data(c_source, name):
    """Extract tile byte array from C source."""
    pattern = rf'const uint8_t {name}_tiles\[\d+\]\s*=\s*\{{([^}}]+)\}}'
    match = re.search(pattern, c_source, re.DOTALL)
    if not match:
        return []
    hex_str = match.group(1)
    return [int(x.strip(), 16) for x in hex_str.split(',') if x.strip()]


def parse_tile_count(c_header, name):
    """Extract TILE_COUNT from header."""
    pattern = rf'#define {name}_TILE_COUNT (\d+)'
    match = re.search(pattern, c_header)
    if match:
        return int(match.group(1))
    return 0


def parse_metasprites(c_source, name):
    """Extract metasprite definitions from C source.

    Returns list of 4 metasprites, each a list of (dy, dx, dtile, props) tuples.
    """
    metasprites = []
    for rot in range(4):
        pattern = rf'const metasprite_t {name}_metasprite{rot}\[\]\s*=\s*\{{([^}}]+)\}}'
        match = re.search(pattern, c_source, re.DOTALL)
        if not match:
            metasprites.append([])
            continue
        body = match.group(1)
        entries = []
        for item in re.finditer(r'METASPR_ITEM\(\s*(-?\d+)\s*,\s*(-?\d+)\s*,\s*(\d+)\s*,\s*S_PAL\((\d+)\)\s*\)', body):
            dy = int(item.group(1))
            dx = int(item.group(2))
            dtile = int(item.group(3))
            pal = int(item.group(4))
            entries.append((dy, dx, dtile, pal))
        metasprites.append(entries)
    return metasprites


def parse_palette(c_source, name):
    """Extract palette RGB8 values from C source.

    Returns list of (r, g, b) tuples.
    """
    pattern = rf'const palette_color_t {name}_palettes\[\d+\]\s*=\s*\{{([^}}]+)\}}'
    match = re.search(pattern, c_source, re.DOTALL)
    if not match:
        return []
    body = match.group(1)
    colors = []
    for item in re.finditer(r'RGB8\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*\)', body):
        colors.append((int(item.group(1)), int(item.group(2)), int(item.group(3))))
    return colors


def signed_byte(val):
    """Convert signed int to unsigned byte for assembly db."""
    if val < 0:
        val = val & 0xFF
    return val


def emit_sprite_defs(out, pieces):
    """Write tile count DEF constants with include guard."""
    out.write('; =============================================================================\n')
    out.write('; AUTO-GENERATED by tools/png2asm.py from png2asset output\n')
    out.write('; Do not edit manually - regenerate with: make gfx\n')
    out.write('; =============================================================================\n\n')

    out.write('IF !DEF(SPRITE_DEFS_INC)\n')
    out.write('DEF SPRITE_DEFS_INC EQU 1\n\n')

    out.write('; Tile counts per piece (unique tiles after deduplication)\n')
    for p in pieces:
        out.write(f'DEF {p["name"]}_TILE_COUNT EQU {p["tile_count"]}\n')

    out.write(f'\nDEF PIECE_COUNT EQU {len(pieces)}\n')
    total_expr = ' + '.join(f'{p["name"]}_TILE_COUNT' for p in pieces)
    out.write(f'DEF TOTAL_SPRITE_TILES EQU {total_expr}\n')

    out.write('\nENDC ; SPRITE_DEFS_INC\n')


def emit_sprite_data(out, pieces):
    """Write all sprite tile data, metasprites, pointer table, and tile offsets."""

    out.write('; =============================================================================\n')
    out.write('; AUTO-GENERATED by tools/png2asm.py from png2asset output\n')
    out.write('; Do not edit manually - regenerate with: make gfx\n')
    out.write('; =============================================================================\n\n')

    out.write('INCLUDE "sprite_defs.inc"\n\n')

    # --- Sprite tile data section ---
    out.write('SECTION "SpriteData_Tiles", ROM0\n\n')
    for p in pieces:
        name = p['name']
        out.write(f'{name}_tiles::\n')
        tiles = p['tiles']
        for t in range(0, len(tiles), 16):
            chunk = tiles[t:t+16]
            hex_bytes = ', '.join(f'${b:02X}' for b in chunk)
            out.write(f'    db {hex_bytes}\n')
        out.write('\n')

    # --- Metasprite definitions section ---
    out.write('SECTION "SpriteData_Metasprites", ROM0\n\n')
    for p in pieces:
        name = p['name']
        for rot in range(4):
            out.write(f'{name}_metasprite{rot}::\n')
            for dy, dx, dtile, pal in p['metasprites'][rot]:
                dy_b = signed_byte(dy)
                dx_b = signed_byte(dx)
                out.write(f'    db ${dy_b:02X}, ${dx_b:02X}, {dtile}, {pal}\n')
            out.write('    db $80\n')
        out.write('\n')

    # --- Metasprite pointer table ---
    out.write('SECTION "SpriteData_MetaspriteTable", ROM0\n\n')
    out.write('_Tetrominos_metasprites::\n')
    for p in pieces:
        name = p['name']
        ptrs = ', '.join(f'{name}_metasprite{r}' for r in range(4))
        out.write(f'    dw {ptrs}\n')
    out.write('\n')

    # --- Tile offset table ---
    out.write('SECTION "SpriteData_TileOffsets", ROM0\n\n')
    out.write('_tileOffsets::\n')
    out.write('    db 0\n')
    cumulative_parts = []
    for p in pieces:
        cumulative_parts.append(f'{p["name"]}_TILE_COUNT')
        cumulative_expr = ' + '.join(cumulative_parts)
        out.write(f'    db {cumulative_expr}\n')
    out.write('\n')


def emit_palette_data(out, colors):
    """Write palette data as raw little-endian RGB555 bytes in its own SECTION."""
    out.write('; =============================================================================\n')
    out.write('; AUTO-GENERATED by tools/png2asm.py from png2asset output\n')
    out.write('; Do not edit manually - regenerate with: make gfx\n')
    out.write('; =============================================================================\n\n')

    out.write('SECTION "PaletteData", ROM0\n\n')
    out.write('Palette_palettes::\n')
    for pal_idx in range(8):
        base = pal_idx * 4
        out.write(f'    ; Palette {pal_idx}\n')
        words = []
        for c in range(4):
            r, g, b = colors[base + c]
            rgb555 = rgb8_to_rgb555(r, g, b)
            lo = rgb555 & 0xFF
            hi = (rgb555 >> 8) & 0xFF
            words.append(f'${lo:02X}, ${hi:02X}')
        out.write(f'    db {", ".join(words)}\n')
    out.write('\n')


def emit_setup_sprites(out, pieces):
    """Write set_sprite_data call sequences for all pieces."""
    out.write('; =============================================================================\n')
    out.write('; AUTO-GENERATED by tools/png2asm.py from png2asset output\n')
    out.write('; Do not edit manually - regenerate with: make gfx\n')
    out.write('; =============================================================================\n\n')

    cumulative_parts = []
    for i, p in enumerate(pieces):
        name = p['name']
        out.write(f'    ; {name}\n')
        if i == 0:
            out.write('    xor a\n')
        else:
            cumulative_expr = ' + '.join(cumulative_parts)
            out.write(f'    ld a, {cumulative_expr}\n')
        out.write(f'    ld b, {name}_TILE_COUNT\n')
        out.write(f'    ld hl, {name}_tiles\n')
        out.write('    call set_sprite_data\n\n')
        cumulative_parts.append(f'{name}_TILE_COUNT')


def main():
    if len(sys.argv) < 3:
        print(f'Usage: {sys.argv[0]} <Tetromino1.c> ... [Pentomino1.c ...] <Palette.c>', file=sys.stderr)
        sys.exit(1)

    # Separate piece files from palette file
    tetromino_files = []
    pentomino_files = []
    palette_file = None
    for f in sys.argv[1:]:
        basename = os.path.basename(f)
        if basename.startswith('Palette'):
            palette_file = f
        elif basename.startswith('Tetromino'):
            tetromino_files.append(f)
        elif basename.startswith('Pentomino'):
            pentomino_files.append(f)

    # Sort each group by number
    tetromino_files.sort(key=lambda f: int(re.search(r'(\d+)', os.path.basename(f)).group(1)))
    pentomino_files.sort(key=lambda f: int(re.search(r'(\d+)', os.path.basename(f)).group(1)))

    # Tetrominoes first, then pentominoes
    all_piece_files = tetromino_files + pentomino_files

    if len(all_piece_files) < 1:
        print('No piece files found', file=sys.stderr)
        sys.exit(1)
    if palette_file is None:
        print('No Palette file found', file=sys.stderr)
        sys.exit(1)

    # Determine output directory from first input file's parent
    out_dir = os.path.dirname(all_piece_files[0])
    if not out_dir:
        out_dir = '.'
    # Go up one level from gen/ to gfx/
    out_dir = os.path.dirname(out_dir)
    if not out_dir:
        out_dir = 'gfx'

    # Parse all piece data
    pieces = []
    for f in all_piece_files:
        with open(f) as fh:
            c_source = fh.read()
        # Also read the .h file for TILE_COUNT
        h_file = f.replace('.c', '.h')
        with open(h_file) as fh:
            h_source = fh.read()
        name = os.path.splitext(os.path.basename(f))[0]
        pieces.append({
            'name': name,
            'tiles': parse_tile_data(c_source, name),
            'tile_count': parse_tile_count(h_source, name),
            'metasprites': parse_metasprites(c_source, name),
        })

    # Parse palette data
    with open(palette_file) as fh:
        pal_source = fh.read()
    palette_colors = parse_palette(pal_source, 'Palette')

    # Write sprite defs (constants only)
    defs_path = os.path.join(out_dir, 'sprite_defs.inc')
    with open(defs_path, 'w') as out:
        emit_sprite_defs(out, pieces)
    print(f'Generated {defs_path}')

    # Write sprite data (tile bytes, metasprites, tables)
    sprite_path = os.path.join(out_dir, 'sprite_data.inc')
    with open(sprite_path, 'w') as out:
        emit_sprite_data(out, pieces)
    print(f'Generated {sprite_path}')

    # Write palette data
    palette_path = os.path.join(out_dir, 'palette_data.inc')
    with open(palette_path, 'w') as out:
        emit_palette_data(out, palette_colors)
    print(f'Generated {palette_path}')

    # Write setup sprites (set_sprite_data call sequences)
    setup_path = os.path.join(out_dir, 'setup_sprites.inc')
    with open(setup_path, 'w') as out:
        emit_setup_sprites(out, pieces)
    print(f'Generated {setup_path}')


if __name__ == '__main__':
    main()
